# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-30 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20191130_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2019, 11, 30, 18, 56, 50, 530495, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_name',
            field=models.CharField(max_length=60),
        ),
    ]
